---
general:
  buildTool: "mta"

service:
  stages:
    Build:
      credentialVariables:
        - name: "AlertNotif"
          credentialId: "susaas-alert-notif"
      # Dynamically create config file during Release Stage
      runFirst:
        command: echo "$AlertNotif" > ./deploy/cf/config/alert-notif-private.json
      credentialVariables:
        - name: "XsSecurity"
          credentialId: "susaas-xs-security"
      # Dynamically create config file during Release Stage
      runFirst:
        command: echo "$XsSecurity" > ./deploy/cf/config/xs-security.json
      credentialVariables:
        - name: "Catalog"
          credentialId: "susaas-catalog"
      runFirst:
        command: |
          # Disable debug mode (turn off echo for all commands and variables)
          set +x

          echo "$Catalog" > ./code/broker/catalog-private.json

          # Enable debug mode (echo commands and variables) again
          set -x
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true

  Additional Unit Tests:
    karmaExecuteTests: false

  Release:
    cloudFoundryDeploy: true

steps:
  npmExecuteLint:
    failOnError: true

  mtaBuild:
    platform: "CF"
    source: "./deploy/cf/"
    extensions: "./mtaext/trial-basic-cicd.mtaext"
    ##### e.g., './mtaext/free-basic-cicd.mtaext'

  cloudFoundryDeploy:
    cfCredentialsId: susaas-cf-credentials
    apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    org: "2e4e072dtrial_cloud-transport-management-system-pkhowode"
    space: "dev"
    mtaDeployParameters: "-f --version-rule ALL"
    mtaExtensionDescriptor: "./deploy/cf/mtaext/trial-basic-cicd.mtaext"
    ################# e.g., './deploy/cf/mtaext/free-basic-cicd.mtaext'
    mtaExtensionCredentials:
      susaas-sb-credentials: susaas-sb-credentials
tmsUpload:  # only relevant once you finish the SAP Cloud Transport Management Expert Feature chapter
  nodeName: 'trial'
  credentialsId: 'tms-sk'
  customDescription: 'TMS Upload'
